-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- BACKGROUND

hl.config({
    background = {
        path = "~/Pictures/Wallpapers/flat-cityscape.jpg",
        blur_passes = 3,
        contrast = 0.8916,
        brightness = 0.8172,
        vibrancy = 0.1696,
        vibrancy_darkness = 0.0,
    },
})
-- NOTE: Section 'background' may be a plugin or custom section; verify the output

-- GENERAL

hl.config({
    general = {
        no_fade_in = false,
        grace = 0,
        disable_loading_bar = false,
    },
})

-- Profie-Photo

hl.config({
    image = {
        path = "~/.config/hypr/catppuccin.png",
        border_size = 2,
        border_color = { "rgba(255", 255, 255, "0)" },
        size = 130,
        rounding = -1,
        rotate = 0,
        reload_time = -1,
        reload_cmd = {  },
        position = { 0, 40 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'image' may be a plugin or custom section; verify the output

-- Day-Month-Date

hl.config({
    label = {
        text = { "cmd[update:1000] echo -e $(date + %A", "%B %d )" },
        color = { "rgba(216", 222, 233, "0.70)" },
        font_size = 25,
        font_family = "JetBrains Mono Nerd",
        position = { 0, 350 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Time

hl.config({
    label = {
        text = "cmd[update:1000] echo <span>$(date + %I:%M%p )</span>",
        color = { "rgba(216", 222, 233, "0.70)" },
        font_size = 120,
        font_family = "SF Pro Display Bold",
        position = { 0, 250 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- USER-BOX

hl.config({
    shape = {
        size = { 300, 60 },
        color = { "rgba(255", 255, 255, ". 1)" },
        rounding = -1,
        border_size = 0,
        border_color = { "rgba(253", 198, 135, "0)" },
        rotate = 0,
        xray = false,
        -- if true, make a "hole" in the background (rectangle of specified size, no rotation)
        position = { 0, -130 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'shape' may be a plugin or custom section; verify the output

-- USER

hl.config({
    label = {
        text = " " .. os.getenv("USER"),
        color = { "rgba(216", 222, 233, "0.80)" },
        outline_thickness = 2,
        dots_size = 0.2,
        -- Scale of input-field height, 0.2 - 0.8
        dots_spacing = 0.2,
        -- Scale of dots' absolute size, 0.0 - 1.0
        dots_center = true,
        font_size = 18,
        font_family = "SF Pro Display Bold",
        position = { 0, -130 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- INPUT FIELD

hl.config({
    input-field = {
        size = { 300, 60 },
        outline_thickness = 2,
        dots_size = 0.2,
        -- Scale of input-field height, 0.2 - 0.8
        dots_spacing = 0.2,
        -- Scale of dots' absolute size, 0.0 - 1.0
        dots_center = true,
        outer_color = { "rgba(0", 0, 0, "0)" },
        inner_color = { "rgba(255", 255, 255, "0.1)" },
        font_color = { "rgb(200", 200, "200)" },
        fade_on_empty = false,
        font_family = "SF Pro Display Bold",
        placeholder_text = "<i><span foreground=##ffffff99 >🔒 Enter Pass</span></i>",
        hide_input = false,
        position = { 0, -210 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'input-field' may be a plugin or custom section; verify the output
