-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock",
        -- prevent multiple instances
        before_sleep_cmd = "loginctl lock-session",
        -- lock before suspend
    },
})

hl.config({
    listener = {
        timeout = 300,
        -- 5 mins
        on_timeout = "loginctl lock-session",
        -- lock screen
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 330,
        -- 5.5 mins
        on_timeout = "hyprctl dispatch dpms off",
        -- turn off monitor
        on_resume = "hyprctl dispatch dpms on",
        -- turn on monitor
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output
