-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        no_fade_in = false,
        grace = 0,
        disable_loading = true,
    },
})

hl.config({
    background = {
        -- Path to your wallpaper - update this to your actual path!
        path = "/home/YOUR_USERNAME/Pictures/wallpapers/yourimage.jpg",
        color = { "rgba(30", 30, 46, "1.0)" },
        blur_passes = 2,
        -- 0 disables blurring
        blur_size = 7,
    },
})
-- NOTE: Section 'background' may be a plugin or custom section; verify the output

hl.config({
    input-field = {
        size = { 200, 50 },
        outline_thickness = 3,
        dots_size = 0.33,
        dots_spacing = 0.15,
        dots_center = true,
        outer_color = { "rgb(180", 190, "254)" },
        -- Lavender
        inner_color = { "rgb(30", 30, "46)" },
        -- Base
        font_color = { "rgb(205", 214, "244)" },
        -- Text
        fade_on_empty = true,
        placeholder_text = "<i>Password...</i>",
        hide_input = false,
        position = { 0, -20 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'input-field' may be a plugin or custom section; verify the output

hl.config({
    label = {
        text = TIME,
        color = { "rgb(205", 214, "244)" },
        font_size = 64,
        font_family = "JetBrainsMono Nerd Font",
        position = { 0, 80 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output
