-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- -----------------------------------------------------

-- Variables

-- -----------------------------------------------------

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- -----------------------------------------------------

-- Applications

-- -----------------------------------------------------

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("kitty"))

-- Open Terminal

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("thunar"))

-- Open File Manager

hl.bind(mainMod .. " + " .. "A", hl.dsp.exec_cmd("~/.config/rofi/scripts/launcher_t2"))

-- Open App Launcher

hl.bind(mainMod .. " + " .. "F", hl.dsp.exec_cmd("brave"))

-- Open Browser (Change to your preference)

hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("cliphist list| rofi -dmenu| cliphist decode| wl-copy"))

-- Clipboard

-- -----------------------------------------------------

-- Window Management

-- -----------------------------------------------------

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

-- Close window

hl.bind(mainMod .. " + " .. "Space", hl.dsp.window.float())

-- Toggle Floating

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- Dwindle effect

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- Change split direction

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- -----------------------------------------------------

-- Workspaces

-- -----------------------------------------------------

-- Switch to the next/previous workspace with mainMod + Control + Arrow Keys
hl.bind(mainMod .. " + CTRL + right", hl.dsp.focus({ workspace = "r+1" }))

hl.bind(mainMod .. " + CTRL + left", hl.dsp.focus({ workspace = "r-1" }))

-- Move active window within the current workspace (Swap positions)
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))

hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))

-- Move active window to the next/prev workspace (Follow the window)
hl.bind(mainMod .. " + CTRL + ALT + right", hl.dsp.window.move({ workspace = "r+1" }))

hl.bind(mainMod .. " + CTRL + ALT + left", hl.dsp.window.move({ workspace = "r-1" }))

-- Move active window to the next/prev workspace silently
hl.bind(mainMod .. " + CTRL + SHIFT + right", hl.dsp.window.move({ workspace = "r+1", silent = true }))

hl.bind(mainMod .. " + CTRL + SHIFT + left", hl.dsp.window.move({ workspace = "r-1", silent = true }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

-- -----------------------------------------------------

-- Functional Bindings (Audio/Brightness/Screenshots)

-- -----------------------------------------------------

hl.bind("Print", hl.dsp.exec_cmd("grim -g $(slurp)-| swappy -f-"))

-- Screenshot tool

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

-- Lock Screen

hl.bind(mainMod .. " + " .. "BackSpace", hl.dsp.exec_cmd("~/.config/rofi/scripts/powermenu_t1"))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- ----------------------------------------------------

-- Keybindings

-- ----------------------------------------------------

hl.bind(mainMod .. " + " .. "slash", hl.dsp.exec_cmd("~/.config/hypr/scripts/keyhint.sh"))
